version: '3.8'

services:
  # ReactJS Client Service
  client:
    build:
      context: ./frontend
    ports:
      - "83:83"
    depends_on:
      - server
    networks:
      - node-network
    volumes:
      - ./frontend:/usr/src/app

  # Express (NodeJS) Server and MongoDB Service
  server:
    build:
      context: ./backend
    image: node-app
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongo:27017/pinvent-app
    depends_on:
      - mongo
    networks:
      - node-network
    volumes:
      - ./backend:/usr/src/app

  # MongoDB Service
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - node-network
    volumes:
      - ./data:/data/db

networks:
  node-network:
    driver: bridge
