services:
  frontend:
    build:
      context: ./frontend
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - 3000:3000
    # stdin_open: true
    # restart: always
    # networks:
    #   - react-express
    depends_on:
      - mongo
  backend:
    build:
      context: ./backend
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "5000:5000"
    # volumes:
    #   - ./backend:/usr/src/app
    #   - /usr/src/app/node_modules
    depends_on:
      - mongo
    # networks:
    #   - express-mongo
    #   - react-express
    # expose: 
    #   - 5000
  mongo:
    image: mongo:6
    ports:
      - 27017:27017

    volumes:
      - slack_db:/data/db
    # networks:
    #   - express-mongo
    # expose:
    #   - 27018
volumes:
   slack_db:
# networks:
#   react-express:
#   express-mongo: